name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-10.15
    steps:
    - name: Run a one-line script
      run: |
        brew list
        # brew install opencv
        python3 -VV
        pip3 install opencv-contrib-python
        python3 -c "import cv2"
